She 14 back nav from subhome to home
seehuasibu/epaper pull request #12
Opened 2017-06-26 02:00 UTC by hoonboon

Current app behaviour:

- Android users can use the OS Back button to navigate to previous screen.
- iOS users will not have this feature.

2017-06-26 02:54 UTC, hutingung requested changes
Take care of the minor comment.

2017-06-26 02:54 UTC, hutingung commented on www/js/app.js
> +    	        console.log('epaper: ' + msgStr);
remove console message.

2017-06-26 07:13 UTC, hoonboon commented
Console log removed as requested.

2017-06-29 10:23 UTC, hutingung approved these changes

2017-06-29 10:24 UTC, merged